#!/usr/bin/env bash

set -euxo pipefail

util_loc="/opt/resource/util.sh"

if [[ ! -f "${util_loc}" ]]; then
  util_loc="./util.sh"
fi

# shellcheck source=./util.sh
source ${util_loc}

input_json="$(cat)"
resource_version_hash=

response=$(query_github_list_repos "${input_json}")
resource_version_hash=$(echo ${response} | version_hash)

# construct the final output
echo "[{\"hash\":\"${resource_version_hash}\"}]"