#!/usr/bin/env bash

set -euo pipefail

source /opt/resource/util.sh

input_json="$(cat)"
resource_version_hash=

response=$(query_github_list_repos "${input_json}")
resource_version_hash=$(echo ${response} | version_hash)

# construct the final output
echo "[{\"hash\":\"${resource_version_hash}\"}]"